example/config/routes.rb
Rails.application.routes.draw do
  resources :razas
  resources :perros

  root 'perros#index'

end

example/app/models/perro.rb
class Perro < ActiveRecord::Base
	belongs_to :raza
end

example/app/models/raza.rb
class Raza < ActiveRecord::Base
	has_many :perros
end

example/app/controllers/perros_controller.rb
class PerrosController < ApplicationController
  before_action :set_perro, only: [:show, :edit, :update, :destroy]

  # GET /perros
  # GET /perros.json
  def index
    @perros = Perro.all
  end

  # GET /perros/1
  # GET /perros/1.json
  def show
  end

  # GET /perros/new
  def new
    @perro = Perro.new
    @razas = Raza.all
  end

  # GET /perros/1/edit
  def edit
    @perro = Perro.find(params[:id])
    @razas = Raza.all
  end

  # POST /perros
  # POST /perros.json
  def create
    @perro = Perro.new(perro_params)

    respond_to do |format|
      if @perro.save
        format.html { redirect_to @perro, notice: 'Perro was successfully created.' }
        format.json { render :show, status: :created, location: @perro }
      else
        format.html { render :new }
        format.json { render json: @perro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perros/1
  # PATCH/PUT /perros/1.json
  def update
    respond_to do |format|
      if @perro.update(perro_params)
        format.html { redirect_to @perro, notice: 'Perro was successfully updated.' }
        format.json { render :show, status: :ok, location: @perro }
      else
        format.html { render :edit }
        format.json { render json: @perro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perros/1
  # DELETE /perros/1.json
  def destroy
    @perro.destroy
    respond_to do |format|
      format.html { redirect_to perros_url, notice: 'Perro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perro
      @perro = Perro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perro_params
      params.require(:perro).permit(:nombre, :edad, :raza_id)
    end
end

example/app/controllers/razas_controller.rb
class RazasController < ApplicationController
  before_action :set_raza, only: [:show, :edit, :update, :destroy]

  # GET /razas
  # GET /razas.json
  def index
    @razas = Raza.all
  end

  # GET /razas/1
  # GET /razas/1.json
  def show
  end

  # GET /razas/new
  def new
    @raza = Raza.new
  end

  # GET /razas/1/edit
  def edit
  end

  # POST /razas
  # POST /razas.json
  def create
    @raza = Raza.new(raza_params)

    respond_to do |format|
      if @raza.save
        format.html { redirect_to @raza, notice: 'Raza was successfully created.' }
        format.json { render :show, status: :created, location: @raza }
      else
        format.html { render :new }
        format.json { render json: @raza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /razas/1
  # PATCH/PUT /razas/1.json
  def update
    respond_to do |format|
      if @raza.update(raza_params)
        format.html { redirect_to @raza, notice: 'Raza was successfully updated.' }
        format.json { render :show, status: :ok, location: @raza }
      else
        format.html { render :edit }
        format.json { render json: @raza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /razas/1
  # DELETE /razas/1.json
  def destroy
    @raza.destroy
    respond_to do |format|
      format.html { redirect_to razas_url, notice: 'Raza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raza
      @raza = Raza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raza_params
      params.require(:raza).permit(:raza_nombre)
    end
end

example/app/helpers/perros_helper.rb
module PerrosHelper
end

example/app/helpers/razas_helper.rb
module RazasHelper
end

example/app/views/perros/_form.html.erb
<%= form_for(@perro) do |f| %>
  <% if @perro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perro.errors.count, "error") %> prohibited this perro from being saved:</h2>

      <ul>
      <% @perro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :edad %><br>
    <%= f.text_field :edad %>
  </div>
  <div class="field">
    <%= f.label :raza_id %><br>
   

<%= collection_select(:perro, :raza_id, @razas, :id, :raza_nombre, prompt: true) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

example/app/views/perros/edit.html.erb
<h1>Editing Perro</h1>

<%= render 'form' %>

<%= link_to 'Show', @perro %> |
<%= link_to 'Back', perros_path %>

example/app/views/perros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Perros</h1>

<table border="1">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Raza</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perros.each do |perro| %>
      <tr>
        <td><%= perro.nombre %></td>
        <td><%= perro.edad %></td>
        <td><%= perro.raza.raza_nombre%></td>
        <td><%= link_to 'Show', perro %></td>
        <td><%= link_to 'Edit', edit_perro_path(perro) %></td>
        <td><%= link_to 'Destroy', perro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perro', new_perro_path %>

example/app/views/perros/new.html.erb
<h1>New Perro</h1>

<%= render 'form' %>

<%= link_to 'Back', perros_path %>

example/app/views/perros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @perro.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @perro.edad %>
</p>

<p>
  <strong>Raza:</strong>
  <%= @perro.raza.raza_nombre %>
</p>

<%= link_to 'Edit', edit_perro_path(@perro) %> |
<%= link_to 'Back', perros_path %>

example/app/views/razas/_form.html.erb
<%= form_for(@raza) do |f| %>
  <% if @raza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raza.errors.count, "error") %> prohibited this raza from being saved:</h2>

      <ul>
      <% @raza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :raza_nombre %><br>
    <%= f.text_field :raza_nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

example/app/views/razas/edit.html.erb
<h1>Editing Raza</h1>

<%= render 'form' %>

<%= link_to 'Show', @raza %> |
<%= link_to 'Back', razas_path %>

example/app/views/razas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Razas</h1>

<table border="1">
  <thead>
    <tr>
      <th>Raza nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @razas.each do |raza| %>
      <tr>
        <td><%= raza.raza_nombre %></td>
        <td><%= link_to 'Show', raza %></td>
        <td><%= link_to 'Edit', edit_raza_path(raza) %></td>
        <td><%= link_to 'Destroy', raza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Raza', new_raza_path %>

example/app/views/razas/new.html.erb
<h1>New Raza</h1>

<%= render 'form' %>

<%= link_to 'Back', razas_path %>

example/app/views/razas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Raza nombre:</strong>
  <%= @raza.raza_nombre %>
</p>

<%= link_to 'Edit', edit_raza_path(@raza) %> |
<%= link_to 'Back', razas_path %>