link/config/routes.rb
Rails.application.routes.draw do
  resources :profesors
 root 'div#index'

  resources :asignaturas
  resources :alumnos
  
end

link/app/models/alumno.rb
class Alumno < ActiveRecord::Base
	belongs_to :asignatura
end

link/app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
	has_many :alumnos
end

link/app/models/profesor.rb
class Profesor < ActiveRecord::Base
end

link/app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
    @asignaturas = Asignatura.all
  end

  # GET /alumnos/1/edit
  def edit
    @alumno = Alumno.find (params[:id])
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:nombre, :apellido, :matricula, :asignatura_id)
    end
end

link/app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  before_action :set_asignatura, only: [:show, :edit, :update, :destroy]

  # GET /asignaturas
  # GET /asignaturas.json
  def index
    @asignaturas = Asignatura.all
  end

  # GET /asignaturas/1
  # GET /asignaturas/1.json
  def show
  end

  # GET /asignaturas/new
  def new
    @asignatura = Asignatura.new
  end

  # GET /asignaturas/1/edit
  def edit
  end

  # POST /asignaturas
  # POST /asignaturas.json
  def create
    @asignatura = Asignatura.new(asignatura_params)

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully created.' }
        format.json { render :show, status: :created, location: @asignatura }
      else
        format.html { render :new }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignaturas/1
  # PATCH/PUT /asignaturas/1.json
  def update
    respond_to do |format|
      if @asignatura.update(asignatura_params)
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully updated.' }
        format.json { render :show, status: :ok, location: @asignatura }
      else
        format.html { render :edit }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaturas/1
  # DELETE /asignaturas/1.json
  def destroy
    @asignatura.destroy
    respond_to do |format|
      format.html { redirect_to asignaturas_url, notice: 'Asignatura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura
      @asignatura = Asignatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignatura_params
      params.require(:asignatura).permit(:nombre, :profesor)
    end
end

link/app/controllers/div_controller.rb
class DivController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

link/app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]

  # GET /profesors
  # GET /profesors.json
  def index
    @profesors = Profesor.all
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
  end

  # GET /profesors/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesors/1/edit
  def edit
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new(profesor_params)

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render :show, status: :created, location: @profesor }
      else
        format.html { render :new }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesors/1
  # PATCH/PUT /profesors/1.json
  def update
    respond_to do |format|
      if @profesor.update(profesor_params)
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @profesor }
      else
        format.html { render :edit }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor.destroy
    respond_to do |format|
      format.html { redirect_to profesors_url, notice: 'Profesor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:nombre, :profesion, :direccion)
    end
end

link/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

link/app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

link/app/helpers/div_helper.rb
module DivHelper
end

link/app/helpers/profesors_helper.rb
module ProfesorsHelper
end

link/app/views/alumnos/_form.html.erb
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_area :apellido %>
  </div>
  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.number_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :asignatura_id %><br>
    <%= collection_select(:alumno, :asignatura_id, @asignaturas, :id, :nombre, prompt: true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

link/app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form' %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

link/app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Alumnos</h1>

<table border="5" >
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Matricula</th>
      <th>Asignatura</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.nombre %></td>
        <td><%= alumno.apellido %></td>
        <td><%= alumno.matricula %></td>
        <td><%= alumno.asignatura.nombre %></td>
        <td class="btn btn-success" ><%=  link_to 'Detalles',  alumno %></td>



 



        <td class="btn btn-info" ><%= link_to 'Editar', edit_alumno_path(alumno) %></td>
        <td class="btn btn-danger" ><%= link_to 'Eliminar', alumno, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Alumno', new_alumno_path %>

link/app/views/alumnos/new.html.erb
<h1>New Alumno</h1>

<%= render 'form' %>

<%= link_to 'Back', alumnos_path %>

link/app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @alumno.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @alumno.apellido %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @alumno.matricula %>
</p>

<p>
  <strong>Asignatura:</strong>
  <%= @alumno.asignatura.nombre%>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>

link/app/views/asignaturas/_form.html.erb
<%= form_for(@asignatura) do |f| %>
  <% if @asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asignatura.errors.count, "error") %> prohibited this asignatura from being saved:</h2>

      <ul>
      <% @asignatura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :profesor %><br>
    <%= f.text_area :profesor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

link/app/views/asignaturas/edit.html.erb
<h1>Editing Asignatura</h1>

<%= render 'form' %>

<%= link_to 'Show', @asignatura %> |
<%= link_to 'Back', asignaturas_path %>

link/app/views/asignaturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Asignaturas</h1>

<table border="5">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Profesor</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @asignaturas.each do |asignatura| %>
      <tr>
        <td><%= asignatura.nombre %></td>
        <td><%= asignatura.profesor %></td>
        <td class="btn btn-success"><%= link_to 'Detalles', asignatura %></td>
        <td class="btn btn-info"><%= link_to 'Editar', edit_asignatura_path(asignatura) %></td>
        <td class="btn btn-danger"><%= link_to 'Eliminar', asignatura, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Asignatura', new_asignatura_path %>

link/app/views/asignaturas/new.html.erb
<h1>New Asignatura</h1>

<%= render 'form' %>

<%= link_to 'Back', asignaturas_path %>

link/app/views/asignaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @asignatura.nombre %>
</p>

<p>
  <strong>Profesor:</strong>
  <%= @asignatura.profesor %>
</p>

<%= link_to 'Edit', edit_asignatura_path(@asignatura) %> |
<%= link_to 'Back', asignaturas_path %>

link/app/views/div/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Logo</a>
  </div>
 
  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><%=  link_to 'Alumnos', alumnos_path  %></li>
      <li><%=  link_to 'Asignaturas', asignaturas_path  %></li>
    
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Profesores <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a <%= link_to 'NuevoProfesor', new_profesor_path %> </a> </li>
          <li><a <%= link_to 'Modificar Profesor', profesors_path %> </a></li>
          <li><a <%= link_to 'Eliminar Profesor', profesors_path %> </a></li> 
          <li class="divider"></li>
          <li><a <%= link_to 'Ver lista', profesors_path  %></a></li>
         
        </ul>
      </li>
    </ul>
 
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Buscar">
      </div>
      <button type="submit" class="btn btn-default">Enviar</button>
    </form>
 
    
  </div>
</nav>

link/app/views/div/new.html.erb
<h1>Div#new</h1>
<p>Find me in app/views/div/new.html.erb</p>

link/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Link</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

link/app/views/profesors/_form.html.erb
<%= form_for(@profesor) do |f| %>
  <% if @profesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profesor.errors.count, "error") %> prohibited this profesor from being saved:</h2>

      <ul>
      <% @profesor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :profesion %><br>
    <%= f.text_area :profesion %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

link/app/views/profesors/edit.html.erb
<h1>Editing Profesor</h1>

<%= render 'form' %>

<%= link_to 'Show', @profesor %> |
<%= link_to 'Back', profesors_path %>

link/app/views/profesors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Profesores</h1>

<table border="5">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Profesion</th>
      <th>Direccion</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesors.each do |profesor| %>
      <tr>
        <td><%= profesor.nombre %></td>
        <td><%= profesor.profesion %></td>
        <td><%= profesor.direccion %></td>
        <td class="btn btn-success" ><%= link_to 'Detalles', profesor %></td>
        <td class="btn btn-info" ><%= link_to 'Editar', edit_profesor_path(profesor) %></td>
        <td class="btn btn-danger" ><%= link_to 'Eliminar', profesor, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Profesor', new_profesor_path %>

link/app/views/profesors/new.html.erb
<h1>New Profesor</h1>

<%= render 'form' %>

<%= link_to 'Back', profesors_path %>

link/app/views/profesors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @profesor.nombre %>
</p>

<p>
  <strong>Profesion:</strong>
  <%= @profesor.profesion %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @profesor.direccion %>
</p>

<%= link_to 'Edit', edit_profesor_path(@profesor) %> |
<%= link_to 'Back', profesors_path %>